const types = {
  CHANGE_COLOR: "CHANGE_COLOR",
  GET_IMAGES: "GET_IMAGES",
  RANDOM_IMAGE: "RANDOM_IMAGE",
  FIRST_IMAGE: "FIRST_IMAGE",
  STOP_BACK: "STOP_BACK",
  FIX_BACK: "FIX_BACK",
  RESTART_SLIDE: "RESTART_SLIDE",
  SLIDE_WORK: "SLIDE_WORK",
};
export default types;
